### ISSUE TITLE
Failed to create OpenGL context for format QSerfaceFormat

### ISSUE THREAD

**Issue by mgcwang** [leovan/SciHubEVA#1]
![2018-05-28 14-18-17-948](https://user-images.githubusercontent.com/30514323/40600082-a5326332-6282-11e8-9265-9e3cae4647ca.png)

试着解决弹窗警告的问题：

因为昨天偶然删除了些和独显驱动有关的文件，电脑一直有些小毛病出现，今天安装这个软件又弹出上图所示问题，所以我索性把驱动重装了一遍，但问题仍未解决；（PS：OpenGL和显卡驱动的关系我没整明白，网上有说两者无关的，又有说某年后驱动集成了OpenGL……，最后，没在继续深究，就将驱动重装了一遍，问题未解决）

然后，我换了种做法，试着将上图红框中的三个dll文件放在Sci-Hub EVA安装目录中，仍然弹出上图。

请问，我尝试的第二种做法还需要做什么设置吗？如何能解决该问题？

电脑系统：Win7 64x； 显卡：AMD Radeon HD 7370M

PS：电脑独立显卡一直有问题，所以安装的显卡驱动是出厂光盘上带的，年代比较久，但是也只能用那个版本号的驱动才好使，不然独显的软件控制面板都打不开，所以，如果解决方案是升级驱动，我可能不能再尝试了。

另外，添加的dll文件是我从微信软件的安装目录中拷贝来的，如下图所示。

![2018-05-28 14-25-27-757](https://user-images.githubusercontent.com/30514323/40601416-ae8b2b44-6287-11e8-9977-79833844303a.png)

**Comment by leovan** [comment]
很抱歉出现这样的问题，首先可以明确的一点是 `libEGL.dll, libGLESv2.dll, d3dcompiler_*.dll` 并未打包进入安装包，所以需要系统环境中有这些动态链接库。经排查，在系统目录中找到了 `d3dcompiler_*.dll`，在 PyQt5 目录中找到了 `libEGL.dll, libGLESv2.dll`。

完美的解决方案肯定是将其打包进入安装包，但仍不清楚 PyInstaller 为何未将其打包，在 PyInstaller 上发现一个 issue 可能与其相关 https://github.com/pyinstaller/pyinstaller/issues/3458 。所以当前的可行解决方案是安装包含 OpenGL 的驱动，如果是 PyInstaller 的问题，如果其在后续版本中修复了，相信可以顺利将相关动态链接库打包。

**Comment by mgcwang** [comment]
谢谢开发者解答，相关问题我已经清楚了。

由于我电脑自身显卡驱动更新到新版后，切换显卡的控制面板无法打开，随带产生其他问题，所以目前我暂时无法更换驱动。不过，该软件还是让我很激动，我会继续关注该软件，并积极推荐给周边的朋友使用。

再次感谢解答！等以后发布的版本可用时，再来留言讨论问题！
