### ISSUE TITLE
Feature: Bulk Downloading\ queue Downloading

### ISSUE THREAD

**Issue by manolovskij** [leovan/SciHubEVA#10]
Downloading files in bulk or in queue you would be pretty useful. Especially when journal volumes have links that end in sequential numbers. This can be done by either an external file the would contain a list of URLs (like wget), or by an in program gui queue.

**Comment by leovan** [comment]
Thanks for the suggestion. Could you please have an example journal volume link for me. I will dig out how to achieve this feature. May be in a more common way that you can download files with links in a file. Since it may change the UI and some key downloading steps, it may take me some time to get this done, hopefully in next release.

**Comment by manolovskij** [comment]
A journal volume may contain articles that have their urls formatted like this: 

https://www.site.org/journal/xxxxx100
https://www.site.org/journal/xxxxx101
https://www.site.org/journal/xxxxx102

And the next volume would be:
https://www.site.org/journal/xxxxx103 
And so on. 

So maybe a command that would download from a range like .../xxxxx100-.../xxxxx150 would be really helpful. 

But even if it just has a file as an input it would be fine, since it is easy to create these ascending lists with a script.

Now I’m not sure how it will work with captchas, if you can input them just once for verification that would be really good. If you input them for every download that’s fine too, it stills saves time.

**Comment by leovan** [comment]
Hi @manolovskij , now it supports downloading with a query list file. It's more common way to download with multiple queries. Hope it helps with your problem.

**Comment by manolovskij** [comment]
I upgraded to version 3.0.0 and the load option for query files started just fine but it got stuck after I input the Captcha. Then I tried downloading from one URL and it also got stuck after the Captcha.

This is where the output gets stuck:

```
[INFO] - Fetching PDF ...
Angel [CAPTCHA] is coming!
```

Then I tried with version 2.1.2 and it worked great, with this output:
```
[INFO] - Fetching PDF ...
[WARNING] - Angel [CAPTCHA] is coming!
[INFO] - Angel [CAPTCHA] down!
[INFO] - Saved PDF as: ...
```

It seem the **3.0.0** has a problem with this.
I run the app under **macOS Mojave 10.14.5**.

**Comment by leovan** [comment]
Hi @manolovskij , sorry for the bugs. Since it's hare to reproduce the captcha situation, with double checking the codes, I still could not find the problems. I will open a new issue to add a fake server to test all situations. Hope fix it in next release.

**Comment by leovan** [comment]
Hi @manolovskij , bug is fixed and range pattern in query is also supported. Try the new release.

**Comment by manolovskij** [comment]
Everything works perfectly. Awesome work, thanks.
