### ISSUE TITLE
Missing dependencies for SOCKS support.

### ISSUE THREAD

**Issue by SimonHu-HN** [leovan/SciHubEVA#12]
WIN8.1系统 采用socks代理，点击rampage之后，报错Missing dependencies for SOCKS support.
请问该如何处理
BTW. 我的分辨率是1920x1080,我打开设置的话，最下面的确认和取消按钮看不见，我只能通过conf文件修改，请问这个是否有可以修正的方法（虽然我通过conf还是可以改的）

**Comment by leovan** [comment]
1. 抱歉之前没有测试过 Socks 代理，只测试了 HTTP 代理，这不是平台问题，是没有安装 Python Socks 相关的包导致的，会在下一个版本中修复该问题，目前请暂时使用 HTTP 代理模式。
2. 1920x1080 理论上是能够看到设置页面所有按钮的，抱歉虚拟机中只有一个 Win 10 环境，不清楚是否是由于系统问题，可否截一个图传上来看一看，下个版本我可以将 `确认` 设置为默认按钮以支持回车键。

**Comment by SimonHu-HN** [comment]
1. 所以我可以通过源码打包一些socks依赖包吗？，不过谢谢我确认了并非是我的电脑出了问题。
2. 我一开始也想用回车的方法，但是没有反应，尽快加入快捷键确实是一个很好的修正方向。图如下
![image](https://user-images.githubusercontent.com/26670764/62831442-e7de7700-bc51-11e9-8130-a7b448306f54.png)

3. star一下，以表敬意。

**Comment by leovan** [comment]
Socks 代理之前没制定版本号，代码上也需要再修复下才能用。你传的图为什么下面有一块是黑的，密码区应该是密文看不见的，能把整个窗口截屏一下吗？

**Comment by SimonHu-HN** [comment]
![image](https://user-images.githubusercontent.com/26670764/62831520-5d971280-bc53-11e9-9240-5feabc4e405c.png)
黑的我也不知道为什么，我是用QQ整个截图的，下面的自然变黑了。这次我手动截了个图，图上显示的区域基本上就是我在电脑屏幕上所能够看到的"设置"区域

**Comment by leovan** [comment]
需要再确定下，这个窗口是不是超过了你电脑的屏幕的高度了呢？如果是的话这个问题应该和分辨率有关，可以尝试修改一下“显示”设置中的“缩放与布局”中的百分比，针对高分辨率屏幕有人会把百分比调高，可能会出现类似问题，你可以尝试调小一点，或者恢复默认100%，不过这个是针对系统全局的修改，对所有应用都会产生作用。

**Comment by SimonHu-HN** [comment]
应该是超出了我的屏幕高度，我向上拖动他的话好像可以略微看到一些原本看不到的区域。
我也按照你的方法正确调整了一下缩放百分比，不过该软件依然没有受到影响。也可能我这个是一个特例，不过我相信在下一个版本加入“确认”快捷键的话是目前最快捷的修复方法。

**Comment by leovan** [comment]
Hi @SimonHu-HN , all done, try the new release.

**Comment by SimonHu-HN** [comment]
> Hi @SimonHu-HN , all done, try the new release.

well done.
