### ISSUE TITLE
about captcha

### ISSUE THREAD

**Issue by LvLH** [leovan/SciHubEVA#13]
Hi, when I get article by PMID, I got the WARN of inputing captcha. Howerer, there's no captcha appear.

**Comment by leovan** [comment]
Hi @LvLH, no captcha means no captcha dialog or captcha dialog with no captcha image?

**Comment by Thommy299** [comment]
Hey leovan,

I have the same problem. The captcha dialog appears but there is no captcha image.

**Comment by leovan** [comment]
@Thommy299 , if it's dialog without captcha image, in most case it's the problem of network. Since the captcha image may not be stored in the same host of pdf, it could have a slow network or even need a proxy to get the image. Try to set a proxy server, it may fix this problem.

**Comment by Thommy299** [comment]
Hey Leovan,

thanks for your help. I have used the proxy server in the application but the captcha images still do not appear. Howeover, this problem only appears if I use a list of URLs to download. If I only use one link, I can see the captcha.

**Comment by leovan** [comment]
Thank for reporting the problem @Thommy299 . I will check this problem later and hope to fix it in next release.

**Comment by leovan** [comment]
Hi @Thommy299 , fortunately I test with downloading with a list just now, and every time (2 DOIs in list) it got different captcha and appeared properly. I will also check the codes, but I think it may not easy to find the solution, since it's hard to get the captcha every time, and it works well in the last test on my computer.

**Comment by leovan** [comment]
Also, I set the captcha url directly in QML UI file, not in python codes (maybe I can download the captcha with python to local, then display with local image). Thus I am not sure the proxy server works well in displaying the captcha. Try to set a system wide proxy to test it (which I used when doing the test above).

**Comment by LvLH** [comment]
> 
> 
> Hi @LvLH, no captcha means no captcha dialog or captcha dialog with no captcha image?

Hi, I got captcha dialog with no captcha image.

**Comment by Thommy299** [comment]
> > Hi @LvLH, no captcha means no captcha dialog or captcha dialog with no captcha image?
> 
> Hi, I got captcha dialog with no captcha image.

I still have the same problem when I working with lists (URLs). I am using the Windows application.

**Comment by leovan** [comment]
@Thommy299 I believe in most cases it's the network problem. Now captcha images are downloaded with proxy too, and captcha iamges are stored in different hosts, set a global proxy then try again. I will add a log to tell whether the captcha images are downloaded completely or not.

**Comment by Thommy299** [comment]
> @Thommy299 I believe in most cases it's the network problem. Now captcha images are downloaded with proxy too, and captcha iamges are stored in different hosts, set a global proxy then try again. I will add a log to tell whether the captcha images are downloaded completely or not.
Thanks for your fast response. I am trying to download with a proxy, however, I get this error message: 

[ERROR] - SOCKSHTTPSConnectionPool(host='sci-hub.se', port=443): Max retries exceeded with url: / (Caused by NewConnectionError(': Failed to establish a new connection: [WinError 10061] 

Do you have an idea how I can fix it?

Thanks!

**Comment by leovan** [comment]
@Thommy299 I guess it's still the network problem. Since you download with a list, I doubt Sci-Hub may block the connection for a while if you download too many papers in a short time period.

**Comment by Thommy299** [comment]
> @Thommy299 I guess it's still the network problem. Since you download with a list, I doubt Sci-Hub may block the connection for a while if you download too many papers in a short time period.

Hi Leovan, thanks for your answer. I also tried changing to the other sci-hub URL, but it doesn't work. So if I am activating the proxy, I get the connection problem. If I don't use the proxy, I don't see the captcha ("WARNING] - Angel [CAPTCHA] is coming!" -- but there is no pop-up) .

I am using a simple .txt as a list input.
