### ISSUE TITLE
captcha window cannot pop-up

### ISSUE THREAD

**Issue by wfc1102** [leovan/SciHubEVA#14]
OS: Windows 10, 64 bit OS
Installation: SciHubEVA-x64-v3.1.2.exe

captcha window doesn't pop-up, thus I cannot type the captcha. Could you help me solve it,  thanks?

**Comment by leovan** [comment]
Could you please provide more information, e.g. query input, logs, and screenshot.

**Comment by leovan** [comment]
It should be fixed, try the new release.
