### ISSUE TITLE
無法下載文獻

### ISSUE THREAD

**Issue by jianzhizhipeng** [leovan/SciHubEVA#15]
不排除是我自己網速的問題。我下載了之前的版本同樣出現這個問題。速度非常慢。停留在fetching的命令行。
但是我更換了電腦之後發現速度依舊很慢。

**Comment by leovan** [comment]
不太清楚你的具体网络环境，fetching 情况多数为网络问题，同时由于 SciHub 服务也不是很稳定，如果存在防火墙问题，建议设置使用代理服务器，或者更换更快的 SciHub 服务地址。

**Comment by jianzhizhipeng** [comment]
我這邊是換過了電腦，也換過了網絡，同時也用了VPN代理。不清楚您說的代理服務器是指專用的sci-hub針對的代理proxy還是？

**Comment by leovan** [comment]
就是一般的代理服务器，如果你在大陆，因为临近国庆，近期可能网络审查会比较严一些，国外服务会慢一些。

**Comment by jianzhizhipeng** [comment]
感謝，那希望後面會變得好一些。我非常appreciate你這個程序。因為我找這樣的程序很久了。真的很感謝。

**Comment by leovan** [comment]
不客气，希望这个小工具能对你的科研有所帮助。
