### ISSUE TITLE
小問題

### ISSUE THREAD

**Issue by jianzhizhipeng** [leovan/SciHubEVA#16]
作者您好，我又來了。發現了以下的三個小問題，望引用：
1. 第一點是昨天的信號不好發現可能是因為命名太長的緣故，今天將自動命名去掉之後，可以正常工作。
2. 但是取消命名之後帶來的問題是軟件是自動覆蓋的，因此許多名稱會覆蓋。測試結果是37篇文章中除去一篇下載不了以外只有34篇文檔。也許是同名的文章被覆蓋了。考慮到這個，選擇了增加「author」作為自動命名，會出現許多unknown的文章，同樣出現覆蓋現象，文章數量為35.
3. Windows 無論是32位系統還是64位系統無法彈出驗證碼。Mac的不存在該問題。

致謝

**Comment by leovan** [comment]
感谢反馈，近期有些忙，晚些会尝试修复和优化这些问题，希望能在下个 Release 搞定这些。

**Comment by jianzhizhipeng** [comment]
再次非常感谢

**Comment by leovan** [comment]
增加了是否覆盖已存在文件的选项，默认不覆盖，会自动在文件名中添加一个时间戳，其他 Bug 应该也修复了，请更新到最新的 Release 试试吧。

**Comment by jianzhizhipeng** [comment]
下载中，万分感谢。


| |
渐之
|
|
linzhipengzhuce@163.com
|
签名由网易邮箱大师定制


在2019年09月26日 14:26，Leo<notifications@github.com> 写道：

增加了是否覆盖已存在文件的选项，默认不覆盖，会自动在文件名中添加一个时间戳，其他 Bug 应该也修复了，请更新到最新的 Release 试试吧。

**Comment by jianzhizhipeng** [comment]
又不排除是網速的原因。但是新版本下載之後輸入captcha之後，總是沒反應。卸載之後恢復舊版本，則可以正常下載。


| |
渐之
|
|
linzhipengzhuce@163.com
|
签名由网易邮箱大师定制


在2019年09月26日 14:26，Leo<notifications@github.com> 写道：

增加了是否覆盖已存在文件的选项，默认不覆盖，会自动在文件名中添加一个时间戳，其他 Bug 应该也修复了，请更新到最新的 Release 试试吧。

**Comment by leovan** [comment]
改逻辑改出了 BUG，紧急修复中，发布后请使用新的 Release。
