### ISSUE TITLE
OpenGL issue

### ISSUE THREAD

**Issue by me0ne0** [leovan/SciHubEVA#18]
When i launch the windows app scihub eva, i get the error that open GL 2.0 or higher driver is required or the ANGLE libraries are missing.

I put missing ANGEL libraries, libegl.dll, libglesv2.dll and d3dcompiler_43.dll in exe folder. exe did not work. Same error.

I tried to updated the intel HD 3000 driver. Its already latest 9.17.10.4459.

Also, i checked my intel HD 3000 is supporting openGL 3.1

I also checked on another laptop, still same issue as that laptop also had the same graphics card intel hd 3000.

For 1st time, when i installed exe in my second laptop, exe ran and hanged up in fetching captcha. Then, closed it and re-ran it OPEN GL error.

I re-installed on both laptops, same error.

switched down to v3.20 still same issue.

Kindly help.

![Capture](https://user-images.githubusercontent.com/28728882/66165483-402c6680-e64e-11e9-98e9-d4cce12a7d84.JPG)
![Capture1](https://user-images.githubusercontent.com/28728882/66165486-402c6680-e64e-11e9-9fbd-eefa12af968a.JPG)

**Comment by me0ne0** [comment]
It was running fine till day before yesterday

**Comment by leovan** [comment]
Maybe I should add OpenGL libraries on Windows like before, see [bbae550](https://github.com/leovan/SciHubEVA/commit/bbae550a6ccd8560e3b1d1f44cf3f3ff655b9141), will fix it in next release.

**Comment by me0ne0** [comment]
looking forward to it. BTW, exe hangs sometimes during captcha fetching. is it because of the connection termination from server?

**Comment by leovan** [comment]
Captcha is downloaded with same setting of pdf, which means it also supports proxy server. In most case, it's network problem to not display it.
