### ISSUE TITLE
出现“获取PDF失败”的情况

### ISSUE THREAD

**Issue by prophesyPPI** [leovan/SciHubEVA#2]
![image](https://user-images.githubusercontent.com/24997521/41496640-2a27c1d8-7177-11e8-8614-702642adec1f.png)
我在 http://sci-hub.nu/ 网页版上可以下载到这篇文献，但在 SciHubEVA 上却不能下载。不知道应该怎样解决。感谢开发者的工作！

**Comment by leovan** [comment]
Hi, @prophesyPPI , 能把你搜索的内容复制给我吗，目前搜索的内容支持URL，POI 和 PMID。

**Comment by prophesyPPI** [comment]
好的，我搜索的内容是：
https://www.researchgate.net/publication/264710497_A_novel_system_for_bi-ocular_eye-tracking_in_vertebrates_with_laterally_placed_eyes

**Comment by prophesyPPI** [comment]
感谢开发者！
