### ISSUE TITLE
Have error running scihub_eva.py

### ISSUE THREAD

**Issue by youyuxiansen** [leovan/SciHubEVA#22]
Dear Leovan，
     Here is a question when I running scihub_eva.py.
1. I generate scihub_resources.py with "pyrcc5 SciHubEVA.qrc -o scihub_resources.py".
![image](https://user-images.githubusercontent.com/35478566/69325198-ba5b8d80-0c84-11ea-8e14-5f57db3e9277.png)

2. Error appears in 
![image](https://user-images.githubusercontent.com/35478566/69325251-d5c69880-0c84-11ea-8e54-0c1909f6a6a4.png)

As you can see, I have imported scihub_resources below.
![image](https://user-images.githubusercontent.com/35478566/69325323-ee36b300-0c84-11ea-8196-f67ba05702df.png)

It still says that cannot find SciHubEVA.qml.

![image](https://user-images.githubusercontent.com/35478566/69325402-10c8cc00-0c85-11ea-9080-060ce89d8238.png)

So could you please tell me where is my problem?
Wish you could reply.

**Comment by leovan** [comment]
Hi @youyuxiansen , you are using the wrong tool to generate the scihub_resources.py. I have change the Qt binding to pyside2 from version 2.0. Now you need generate the scihub_resources.py with `pyside2-rcc SciHubEVA.qrc -o scihub_resources.py`. More details about the building, please refer `building/README.md`.

**Comment by youyuxiansen** [comment]
Oh，I see, amazing, thank you!
