### ISSUE TITLE
Can't find scihub_resources file

### ISSUE THREAD

**Issue by shiiuen01** [leovan/SciHubEVA#23]
the scihub_eva.py has a decalre “import scihub_resources” in line25.
but I can't find scihub_resources file in the entire source code.
Is anything misunderstanding in me ？

**Comment by leovan** [comment]
`scihub_resources.py` is generated by `pyside2-rcc SciHubEVA.qrc -o scihub_resources.py`, it compiles resources into python bytes code. More details, please refer `building/README.md`
