### ISSUE TITLE
Add Linux target when compiling/release

### ISSUE THREAD

**Issue by soppelmann** [leovan/SciHubEVA#24]
Application is built with qt and python, should be easy to compile for and run on linux.

**Comment by leovan** [comment]
It uses `Qt.labs.platform` model which is not supported with some distribuation of Linux. Next major release is on the way (but may not too soon), I will try to add some compatible codes and release a compiled version with something like AppImage.

**Comment by leovan** [comment]
fix with <https://github.com/leovan/SciHubEVA/commit/43f2e6e1345735df5824297b43762c0f0d394ef2>.
