### ISSUE TITLE
WARNING

### ISSUE THREAD

**Issue by liuenqian** [leovan/SciHubEVA#25]
正在处理 3/10 查询 ...

[INFO] - 正在处理搜索: 10.4193/Rhin13.112
[INFO] - 使用 Sci-Hub URL: https://sci-hub.tw
[INFO] - 搜索类型: DOI
[INFO] - 获取 PDF URL 中 ...
[INFO] - 获取到 PDF URL: https://direct.sci-hub.tw/www.rhinologyjournal.com/160c88652d47d0be60bfbfed25111412/www.rhinologyjournal.com@1190.pdf#view=FitH
[INFO] - 获取 PDF 中 ...
[WARNING] - 使徒 [CAPTCHA] 来袭！

sometimes, it stoped. How to skip the issue.

**Comment by leovan** [comment]
[WARNING] - 使徒 [CAPTCHA] 来袭！

表示 SciHub 要求输入验证码才能继续下载，如果未弹出对话框一般是由于网络原因导致验证码图片下载缓慢或者失败，如果有可用的 VPN 可以在设置中配置。一般验证码是由于当前 IP 下载过于频繁导致。

**Comment by liuenqian** [comment]
我想问一下，我不知道VPN那个怎么填进去，我的vpn就是一个订阅地址

**Comment by leovan** [comment]
这个就需要根据你的 VPN 软件的具体情况设置了，你可以自行 Google 一下。
