### ISSUE TITLE
always chinese

### ISSUE THREAD

**Issue by njulhy** [leovan/SciHubEVA#26]
The interface is always in Chinese, even after reinstall(empty the temp file is useless too, e.g. uninstall and delete temp file in C:\Users\PC\AppData\Local). 
Maybe SciHubEVA automatically apply system language, it's cool but I think the word "rampage" should be rename as "download", or just change "暴走" to "下载" because it is stupid to use the word "暴走" here.
Below is my system information:
![2020-08-07_152508](https://user-images.githubusercontent.com/48231508/89620435-36087380-d8c2-11ea-8a47-8ad1fb8c5619.jpg)

**Comment by leovan** [comment]
软件自动应用系统语言，暂时无法人工指定，删除 translations 目录中的中文翻译文件 `SciHubEVA_zh_CN.qm` 文件后，在找不到系统对应的语言文件时会默认采用英文。软件中一些词汇来自动漫「新世纪福音战士」，属于个人喜好。So sorry, please leave it or modify it to whatever you like and compile it with yourself.
