### ISSUE TITLE
下载

### ISSUE THREAD

**Issue by liuenqian** [leovan/SciHubEVA#27]
[INFO] - 正在处理搜索: 10.1143/JJAP.45.4241
[INFO] - 使用 Sci-Hub URL: https://sci-hub.se
[INFO] - 搜索类型: DOI
[INFO] - 获取 PDF URL 中 ...
[INFO] - 获取到 PDF URL: https://cyber.sci-hub.se/MTAuMTE0My9qamFwLjQ1LjQyNDE=/chang2006.pdf#view=FitH
[INFO] - 获取 PDF 中 ...

这种不知道为什么不能自动跳过，经常会卡在一篇

**Comment by leovan** [comment]
一帮情况下是网络问题，服务器在国外下载会慢甚是会断掉，可以尝试重启再下载试试，如果有VPN可以是配置VPN试试。

**Comment by liuenqian** [comment]
VPN我开启了全局模式，貌似我这个vpn不支持在软件里面直接设置，不知道设置为全局模式可以用吗


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Leo <notifications@github.com&gt;
发送时间: 2020年8月9日 09:15
收件人: leovan/SciHubEVA <SciHubEVA@noreply.github.com&gt;
抄送: Ten <1193061840@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[leovan/SciHubEVA] 下载 (#27)





 
一帮情况下是网络问题，服务器在国外下载会慢甚是会断掉，可以尝试重启再下载试试，如果有VPN可以是配置VPN试试。

**Comment by leovan** [comment]
如果能设置成为系统全局的VPN，应该也是可以的。

**Comment by liuenqian** [comment]
我其实卡住之后就关掉再打开，然后再次下载还是那篇卡住，有办法可以设置为这篇无法下载的话就直接跳过、然后再全部结束后提醒那个没成功。比如单篇下载时间超过多少后自动跳到下一篇。
想问，打开了vpn全局后，eva里面不需要特殊设置吗？ &nbsp;谢谢。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Leo <notifications@github.com&gt;
发送时间: 2020年8月9日 09:18
收件人: leovan/SciHubEVA <SciHubEVA@noreply.github.com&gt;
抄送: Ten <1193061840@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[leovan/SciHubEVA] 下载 (#27)

**Comment by leovan** [comment]
配置中有个超时设置，但有些情况下不起作用，这个一直没去弄，因为和验证码一样，”超时“在调试的时候不是很好复现。这个我争取在下一个版本的时候再弄弄看。P.S. 开启全局VPN理论上不需要再软件里面再配置，不过有些VPN的IP也会被SciHub禁掉，这也可能是无法下载的一个原因。

**Comment by liuenqian** [comment]
好的，谢谢啦，我再尝试尝试


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Leo <notifications@github.com&gt;
发送时间: 2020年8月9日 09:26
收件人: leovan/SciHubEVA <SciHubEVA@noreply.github.com&gt;
抄送: Ten <1193061840@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[leovan/SciHubEVA] 下载 (#27)





 
配置中有个超时设置，但有些情况下不起作用，这个一直没去弄，因为和验证码一样，”超时“在调试的时候不是很好复现。这个我争取在下一个版本的时候再弄弄看。P.S. 开启全局VPN理论上不需要再软件里面再配置，不过有些VPN的IP也会被SciHub禁掉，这也可能是无法下载的一个原因。

**Comment by leovan** [comment]
不客气
