### ISSUE TITLE
Build size on macOS

### ISSUE THREAD

**Issue by Albert-Z-Guo** [leovan/SciHubEVA#28]
Hi Leo, when I upgraded SciHubEVA to 4.1.1 through brew on macOS I noticed the build size is ~193MB. Is there a particular reason that it's taking a lot of space on disk?

Many thanks ahead for reading this question. This project is awesome!

**Comment by leovan** [comment]
Uncompress size of SciHubEVA is about 200MB on both macOS and Windows. This is because it's not native app, it's based on Python and Qt, which requires many 3rd party libraries. Also I believe this is a common problem for those app built against cross platform frameworks, such as electron.

**Comment by Albert-Z-Guo** [comment]
Ah I see. Thanks for the explanation!
