### ISSUE TITLE
URL出现问题

### ISSUE THREAD

**Issue by Chikit-L** [leovan/SciHubEVA#33]
由于自带的Url①https://sci-hub.se 卡在下载pdf一步，于是自己添加了②https://www.sci-hub.ren/ 链接，然后将①删除，之后URL栏出现了链接③，继续删除掉③之后URL变成空白，但是可用②链接获取地址（但是还是卡在下载PDF一步）。
在多次尝试加速器之后，eva彻底丢失链接，无法获取链接,提示如下：
2021-06-04 20:30:59,769 - INFO - 获取 PDF URL 中 ...
2021-06-04 20:30:59,770 - ERROR - 获取 PDF URL 失败！
2021-06-04 20:30:59,771 - ERROR - Invalid URL '': No schema supplied. Perhaps you meant http://?

目前URL栏添加地址无效，删除时也提示无法删除空白，重装也无法恢复默认，导致目前软件获取不到任何链接。

**Comment by leovan** [comment]
1. 链接③ 是什么？
2. 无法添加或者提示无法删除请发下截图。

**Comment by Chikit-L** [comment]
抱歉，我不记得链接③的内容了了，当时感觉不是自己添加的也没有多想，直接删除掉了
在添加地址时如图1，点击确定后，变成图2，程序没有任何反应，地址栏无任何变化。
删除地址时如图3，但此时地址栏仍然是空白的。
谢谢大佬回复。
![11](https://user-images.githubusercontent.com/57130625/120893665-0abbf580-c647-11eb-8aec-cec65bcd2d6c.jpg)
![12](https://user-images.githubusercontent.com/57130625/120893667-0c85b900-c647-11eb-934c-aeea4800f522.jpg)
![13](https://user-images.githubusercontent.com/57130625/120893670-0db6e600-c647-11eb-81bd-f5d3cc21c647.jpg)

**Comment by leovan** [comment]
不是很好复现你的问题，你直接删除 `C:\Users\<用户名>\AppData\Roaming\leovan.me\SciHubEVA.ini` 配置文件，再重启程序。这样可以恢复默认设置。

**Comment by Chikit-L** [comment]
谢谢大佬，已经成功解决
