### ISSUE TITLE
Errors----fail to obtain PDF URL

### ISSUE THREAD

**Issue by Shunsenhuang-123** [leovan/SciHubEVA#36]
Hi, leovan
Thank your contribution on this attractive software.
I got a problem when I used the SciHubEVA. The problem is that when I clicked the RAMPAGE button, there was an error—— it said that it fails to obtain PDF URL, and "unvalid <ifram>!", it also reminds me to handle it manually. Although I have changed several different SciHub URL, the problem still exists. What should I do to solve this error, since I have to download enormous literature.

**Comment by leovan** [comment]
Show me your query please, and I will check.

**Comment by leovan** [comment]
Close since no response.
