### ISSUE TITLE
Question about mac

### ISSUE THREAD

**Issue by herjccc** [leovan/SciHubEVA#39]
Hello
I download the dgm on my mac but it failed to be settled down. My computer alarmed me a popup as this dgm was broken. So I am wondering would u mind tell me what I should do?

Thank u.

**Comment by leovan** [comment]
You can try to download it again, maybe the dmg file was not downloaded completely.

**Comment by herjccc** [comment]
No it still does not work. You may see this picture here
<img width="473" alt="Screen Shot 2021-09-14 at 7 27 39 PM" src="https://user-images.githubusercontent.com/77926258/133346941-f25429bc-3a77-453a-b9ad-c06df244ca26.png">

**Comment by herjccc** [comment]
Is that anything damaged from this dmg? I just downloaded the dmg in the file only. Should I download the sources package?

**Comment by herjccc** [comment]
I guess the problem only exists in 5.0 dmg, as I tried 4.11 it can be opened

**Comment by herjccc** [comment]
If I employed 4.11

 19:54:37,145 - INFO - Using Sci-Hub URL: https://sci-hub.se
2021-09-14 19:54:37,146 - INFO - Query type: DOI
2021-09-14 19:54:37,146 - INFO - Fetching PDF URL ...
2021-09-14 19:54:38,480 - ERROR - Failed to get PDF URL!
2021-09-14 19:54:38,480 - ERROR - No valid <iframe>!
2021-09-14 19:54:38,480 - INFO - You may need handle it manually.
2021-09-14 19:54:38,480 - INFO - Request URL: https://sci-hub.se/10.1016/j.pubrev.2011.04.002
2021-09-14 19:54:38,480 - INFO - Response URL: https://sci-hub.se/10.1016/j.pubrev

**Comment by leovan** [comment]
https://sci-hub.se site is down. Try another one. Also, app use GET method to fetch pdf, but the sci-hub website has changed. Need some time to fix this problem.

**Comment by herjccc** [comment]
> https://sci-hub.se site is down. Try another one. Also, app use GET method to fetch pdf, but the sci-hub website has changed. Need some time to fix this problem.

Yes. Sadly, I found they changed another link. 
Hope u can work out! Pls notify me if you have done that successful. Thank u.

**Comment by leovan** [comment]
Please download the latest release to fix this problem.
