### ISSUE TITLE
the latest version is damaged

### ISSUE THREAD

**Issue by min1992** [leovan/SciHubEVA#42]
Hi,

I downloaded several times of latest version, while it always displayed damaged. I wonder whether it's just damaged in GitHub.  Could you please check the latest version?  Thank you so much.

 Best wishes!

**Comment by leovan** [comment]
If you have macOS, try `brew install --cask scihubeva`. Brew version is also the latest release and it automatically checked it works well. If you have windows, try download it again. Most damaged problem is due to the network, it may not finish downloading.

**Comment by leovan** [comment]
I could not see the screenshot, you can try the following steps:
1. `System Preferences` - `Security & Privacy` - `Allow apps downloaded from:` - `Anywhere`.
2. run `sudo xattr -rd com.apple.quarantine /Applications/SciHubEVA.app` in terminal.

**Comment by grysophia** [comment]
Hi Leo,

Thank you! I have changed the system preference and run the command "sudo
xattr -rd com.apple.quarantine /Applications/SciHubEVA.app" in terminal. It
appears that SciHubEVA is working now!

Best,
Sophia

Leo ***@***.***> 于2021年10月31日周日 上午2:42写道：
