### ISSUE TITLE
这个最新版本对苹果电脑系统版本有要求吗？

### ISSUE THREAD

**Issue by liuenqian** [leovan/SciHubEVA#43]
我下载了最新版本，发现自己的电脑打不开这个软件，谢谢。

**Comment by leovan** [comment]
应该比较新的版本都 OK，这个没具体测试过，你可以发一下你的系统版本，打不开具体什么状态，有没有错误信息，方便的话可以截图看一下。

**Comment by liuenqian** [comment]
![image](https://user-images.githubusercontent.com/64129965/140459760-61431b28-a395-4271-8724-8b997708031d.png)
我安装成功后，打开app就是跳一下，app就消失了。

**Comment by leovan** [comment]
#42 尝试根据这个 issue 里面的我的回复运行一些命令试一试看。

**Comment by liuenqian** [comment]
好的  谢谢了

**Comment by liuenqian** [comment]
![image](https://user-images.githubusercontent.com/64129965/140460764-b6c913f3-50d7-4da4-a8e2-fdf9d1f6ad34.png)
我试过了 还是不行

**Comment by leovan** [comment]
软件最新版升级了 Qt 至 6.2，这个版本最低支持 macOS 的版本为 10.14，看你的截图是 10.13，https://doc.qt.io/qt-6/macos.html，估计是这个原因了。

**Comment by liuenqian** [comment]
好的好的
