### ISSUE TITLE
ERROR - HTTPSConnectionPool(host='sci-hub.hkvisa.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

### ISSUE THREAD

**Issue by Ziqian-xia** [leovan/SciHubEVA#47]
Hi leovan,
I came across a ERROR in using this tool and I am not sure where I went wrong. 
The connection to Sci-hub is OK, and the my input my files look like this：

** A text file**
10.1016/j.ecolecon.2015.04.003
10.1016/j.jenvman.2009.09.010
...

**This is the returning log**
2022-02-11 23:42:18,521 - ERROR - HTTPSConnectionPool(host='sci-hub.hkvisa.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

**Comment by leovan** [comment]
It seems a networking problem. Also I try to search `10.1016/j.ecolecon.2015.04.003`, it fails due to the pdf url extraction bug from the web page. I will fix this soon.
