### ISSUE TITLE
MacBook上安装完后，软件打不开，显示“已损坏，无法打开“

### ISSUE THREAD

**Issue by Echo7998** [leovan/SciHubEVA#48]

**Comment by leovan** [comment]
软件没有签名，且目前没有原生支持 M1 芯片的 macOS 系统，如果是 M1 芯片，请「右键」选择「显示简介」，勾选「使用 Rosetta 打开」。如果是 Intel 芯片，请自行 Google 一下没有签名软件打开的方式就行了。
