### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by 17092310888** [leovan/SciHubEVA#56]
Hello, I would like to ask, when the latest version 6.0 of sci-hubEVA was downloaded, I was prompted: ERROR - search list file is not a text file! But I exported notepad files directly from endnote. Is there any solution for this? Thank you.

**Comment by leovan** [comment]
It was reported the same problem by others before. Reason is that the txt file exported from EndNote was encoded with some extra information which leads the SciHubEVA not recognizing it as a regular txt file. You can create a new txt file, then copy the content from the exported file to it. Sugguest you save the new txt file with UTF-8 character set.

**Comment by 17092310888** [comment]
非常感谢您的解答，刚刚手动粘贴了几个sci-hub数据库里有的几个文献的doi进txt文件中，然后尝试了ANSI、Unicode、Unicode big endian、UTF-8四种编码，结果除了ANSI编码的，其他三种都提示“搜索列表不是一个文本文件”，但ANSI编码的跑起来提示“获取 PDF URL 失败”，请问有解决办法吗？

**Comment by leovan** [comment]
获取 PDF URL 部分代码有些问题，这两天修复吧，等发布新版本后下载最新的版本吧。

**Comment by 17092310888** [comment]
嗯好的，非常感谢您的耐心解答，还麻烦您在github和邮箱双线程回复，不好意思，哈哈哈。
祝您生活愉快！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leovan/SciHubEVA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月25日(星期四) 上午9:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [leovan/SciHubEVA] Bug report (Issue #56)





 
获取 PDF URL 部分代码有些问题，这两天修复吧，等发布新版本后下载最新的版本吧。

**Comment by 17092310888** [comment]
您好，我有个错误报告，就是6.1版本跑起来之后，它在下载一些文献时（Sci-hub上有的文献）会一直提示获取PDF中，但几个小时也下载不完成也不终止。
再次感谢您的分享，祝您生活愉快！







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月25日(星期四) 上午9:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [leovan/SciHubEVA] Bug report (Issue #56)





 
获取 PDF URL 部分代码有些问题，这两天修复吧，等发布新版本后下载最新的版本吧。
 
&mdash;

**Comment by leovan** [comment]
猜测可能是网络问题，如果方便你可以把卡住的查询条件发一下，这边调试下看看是什么原因。

**Comment by 17092310888** [comment]
不好意思，那个doi找不到了，后面如果发现了，再发给您。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leovan/SciHubEVA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月28日(星期天) 中午11:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [leovan/SciHubEVA] Bug report (Issue #56)





 
猜测可能是网络问题，如果方便你可以把卡住的查询条件发一下，这边调试下看看是什么原因。
