### ISSUE TITLE
macOS downloads 6.2.3 still contain version number 6.2.2

### ISSUE THREAD

**Issue by suschizu** [leovan/SciHubEVA#57]
hello! the latest mac build's info.plists weren't updated to 6.2.3

https://github.com/leovan/SciHubEVA/releases/download/v6.2.3/SciHubEVA-arm64-v6.2.3.dmg
https://github.com/leovan/SciHubEVA/releases/download/v6.2.3/SciHubEVA-x86_64-v6.2.3.dmg

```
<key>CFBundleShortVersionString</key>
    <string>6.2.2</string>
```

<img width="637" alt="Screenshot 2023-09-10 at 20 25 01" src="https://github.com/leovan/SciHubEVA/assets/16004333/8ff64514-8625-42f6-a2d5-5674b9e5d2f3">

**Comment by leovan** [comment]
Yes, I can see this problem, will fix it in next version.

**Comment by suschizu** [comment]
thanks!
