### ISSUE TITLE
大批量下载占用内存过高

### ISSUE THREAD

**Issue by leoschopen** [leovan/SciHubEVA#58]
大批量下载pdf的时候，占用内存是不断增加的，尤其是下载1k个文件以后，甚至超过下载文件的总大小，不知道这个机制是什么，有无解决办法？

**Comment by leoschopen** [comment]
> 批量任务可能没有及时清理相关内存，争取在下一个版本时优化下。

期待更新

**Comment by leovan** [comment]
做了一些优化，应该是修复了，试一下最新版，还有问题的话再开 issue。
