### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by id88** [leovan/SciHubEVA#6]
你好！
我使用的是Windwos10 ，按照 BUILDING.md 文件中的步骤，我已经安装了 Qt 并且能够执行 lupdate 和 lrelease 命令。在执行 lupdate SciHubEVA.pro 的时候出现了这样一个错误：
```bash
WARNING: Project ERROR: Unknown module(s) in QT: quickcontrols2
F:/SciHubEVA-master/scihub_api.py:83: Excess closing bracket in C++ code (or abuse of the C++ preprocessor)
F:/SciHubEVA-master/scihub_api.py:83: Excess closing parenthesis in C++ code (or abuse of the C++ preprocessor)
F:/SciHubEVA-master/scihub_api.py:83: Excess closing parenthesis in C++ code (or abuse of the C++ preprocessor)
F:/SciHubEVA-master/scihub_api.py:83: Excess closing parenthesis in C++ code (or abuse of the C++ preprocessor)
F:/SciHubEVA-master/scihub_api.py:83: Unterminated C++ character
F:/SciHubEVA-master/scihub_api.py:104: Unterminated C++ character
F:/SciHubEVA-master/scihub_api.py:107: Unterminated C++ character
...(省略)
```
这是缺少 quickcontrols2 模块吗？我Google了好久都没有找到解决方案，另外下面 C++ 是有什么错误啊？

**Comment by leovan** [comment]
这是 Warning，应该不影响的，因为 Python 代码中也有需要翻译的东西，所以在 pro 工程文件中我们将包含待翻译字符串的文件都加入了 lupdate_only { SOURCES } 中，所以用 Qt 的 lupdate 也会识别到这些 Python 文件，但其肯定不能处理 Python 中的翻译，所以后面还需要用 `pylupdate5 SciHubEVA.pro`。不过因为翻译源文件 (.ts) 我已经生成并添加了中文翻译，所以其实不用 `lupdate` 和 `pylupdate5`，直接用 `lrelease SciHubEVA.pro` 生成翻译文件 (.qm) 即可。
