### ISSUE TITLE
Application is damaged can't open

### ISSUE THREAD

**Issue by ricounet67** [leovan/SciHubEVA#60]
I have an issue with the last version of Scihub-Eva: when I open the application it fails, and I have a message “Application is damaged and can't be opened. You should put this element in Trash“

I tried installing with the GitHub dmg and with HomeBrew.

When I compile the application by myself, it works

**Comment by leovan** [comment]
Because this App is not signed with an apple developer id certificate. You can refer <https://iboysoft.com/news/app-is-damaged-and-cannot-be-opened.html> to solve this problem.
