### ISSUE TITLE
I don't know why my system (wsl2 ,  Ubuntu22.04 )could not run the latest appimage

### ISSUE THREAD

**Issue by NanKu257** [leovan/SciHubEVA#61]
/tmp/.mount_SciHubYvhawg/AppRun: line 8: 10804 Segmentation fault      ${APP_DIR}/SciHubEVA

**Comment by leovan** [comment]
I guess it may be the problem of WSL2. I only test on desktop version ubuntu in virtual machine. I will test it on WSL2 later to see whether I can fix the problem.

**Comment by NanKu257** [comment]
Thank you for taking the time to respond to my questions，I've also tried a few previous versions of appmage and they all get the same error.

**Comment by leovan** [comment]
I tested on WSL2 and got the same error. And there is no more error message, it's diffcult to debug. So I cannot fix this problem, recommand use the windows version instead. Linux version only tested to work on desktop version linux not wsl version.
