### ISSUE TITLE
求助！win10 打包失败

### ISSUE THREAD

**Issue by lveagle** [leovan/SciHubEVA#7]
你好！

    我在win10上可以运行，但是用pyinstaller打包运行失败，pyinstaller是最新的3.4，我想问题可能就是这个(https://github.com/pyinstaller/pyinstaller/pull/3875)。

    请问你是在Windows上打包成功的吗，还是Mac呢？我试了下就算是最简单的只是调用qml文件，也打包不成功，有什么办法吗？

**Comment by lveagle** [comment]
问题已经解决了，原来是生成exe的过程中有一些dll，不知道是损坏了还是什么的原因 ，比原来要大了一些，导致读取不了，逐个替换然后就可以运行了。

**Comment by leovan** [comment]
Use the latest develop version pyinstaller instead. A simple way to fix the `QT_INSTALL_QML` path problem is setting the path mannually. e.g.

Patch the function `qt5_qml_dir()` in `hook-PySide2.QtQuick.py`

```python
qmldir = os.environ['QT_INSTALL_QML']
```

Set the PATH manually before building on macOS

```bash
export QT_INSTALL_QML=/PYATHON_ROOT/lib/python3.7/site-packages/PySide2/Qt/qml
```

or on Windows:

```bat
set QT_INSTALL_QML=X:\PYTHON_ROOT\Lib\site-packages\PySide2\qml
```
