### ISSUE TITLE
2.0.0 版本 验证码无法显示

### ISSUE THREAD

**Issue by GTLeoLee123** [leovan/SciHubEVA#8]
DOI：10.1016/j.coldregions.2013.01.005
无法正常显示验证码情况。
![image](https://user-images.githubusercontent.com/46435605/50750730-45a47e00-1281-11e9-85a0-0f1f30c45c6f.png)

![image](https://user-images.githubusercontent.com/46435605/50750710-31f91780-1281-11e9-9ab0-f150ecc0de40.png)

**Comment by leovan** [comment]
测试了很多次，成功命中一次验证码，验证码是可以显示的，不过忘记截图了 (记录了验证码地址：https://zero.sci-hub.tw/img/5c32e7cc7ae56.jpg，不过这个已经失效，应该是临时产生的)，后面就再也没有成功出现需要输入验证码的情况了。因为验证码很少出现，所以不是很好复现问题，目测是因为网络比较慢，图片没有缓冲出来的原因。

**Comment by GTLeoLee123** [comment]
谢谢您及时回复。具体情况也不太清楚，我对两台win7电脑安装使用，均无法出验证码。我采用网页版SciHub时，验证码照常显示。我使用本软件对另外一个DOI进行进行下载，弹出验证码。我放置5分钟，也未出现。
如因系统版本旧问题，由于验证码很少出现，这类我能采用网页版进行单独下载。
